import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <main className="w-full max-w-screen-2xl mx-auto">
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
